version: 2.1

orbs:
  architect: giantswarm/architect@6.5.0

workflows:
  test:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main
                - master
